services:
  codeserver:
    build: .
    container_name: codeserver-main
    ports:
      - "${EXTERNAL_PORT:-8080}:8080"
    environment:
      - PASSWORD=${PASSWORD}
      - OLLAMA_HOST=${OLLAMA_BASE_URL:-http://localhost:11434}
      - GIT_AUTHOR_NAME=${GIT_USER_NAME:-CodeServer}
      - GIT_AUTHOR_EMAIL=${GIT_USER_EMAIL:-codeserver@localhost}
    volumes:
      # Persistent workspace
      - ./workspace:/workspace
      - ./vscode-config:/home/vscode/.config
      
      # SSH keys (if available)
      - .ssh:/home/vscode/.ssh:ro
      
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
